In [1]:
import numpy as np
import pandas as pd

## Array 1D

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [2]:
# Criando um array 1 dimensão
ar_1d = np.random.randn(5)
print(ar_1d)
print(ar_1d.shape)

[-1.06889957  1.38817416  1.02013965 -0.26039972 -1.24055318]
(5,)


## Array 2D

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [3]:
# Criando um array com 2 linhas e 3 colunas
ar_2d = np.random.randn(2,3)
print(ar_2d)
print(ar_2d.shape)

[[-0.09890882  1.38782921  1.83995294]
 [-0.15268205  0.54874622 -1.13888515]]
(2, 3)


## Array 3D

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [4]:
# Criando um array com 3D
ar_3d = np.random.randn(3,3,2)
print(ar_3d)
print(ar_3d.shape)

[[[ 0.55073949  0.25542605]
  [ 0.44302514  0.68028749]
  [ 2.42658664 -0.63766174]]

 [[ 0.44328829  0.81970165]
  [-0.34492188 -0.247601  ]
  [ 2.08003763  0.43753562]]

 [[-0.89797877  0.25713174]
  [-0.41720455  0.92783368]
  [ 0.85234216 -1.04050262]]]
(3, 3, 2)


## Array 4D

In [5]:
ar_4d = np.random.randn(3,3,2,2)
print(ar_4d)
print(ar_4d.shape)

[[[[-1.53333698  0.53553967]
   [ 1.24188746 -1.50101192]]

  [[ 0.81526099 -0.17365253]
   [ 0.36806727 -0.77573435]]

  [[ 0.70531284 -1.14907458]
   [ 0.39227294 -0.3320145 ]]]


 [[[-0.68262017 -0.4710064 ]
   [ 1.21883809 -0.74024536]]

  [[-2.30875156  0.71418579]
   [-0.16713489  1.77054902]]

  [[-1.04581505  0.24638364]
   [-0.54543486 -0.36056931]]]


 [[[-1.33709403 -0.59053207]
   [ 0.56722     1.23563233]]

  [[ 0.10210234 -0.09718359]
   [-0.8508949  -1.33517233]]

  [[ 0.89729182 -1.75664928]
   [-2.08078373 -0.0800913 ]]]]
(3, 3, 2, 2)


## Array 1D - Lista de Valores

In [6]:
array_01 = [1,2,3]
array_01 = np.array(array_01)
print(array_01)
print(type(array_01))

[1 2 3]
<class 'numpy.ndarray'>


## Array 2D - Lista de Valores

In [7]:
array_02 = [[1,2,3],[4,5,6]]
array_02 = np.array(array_02)
print(array_02)
print(type(array_02))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Array Com Valor Zero

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Com Valor Um

In [11]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tipo de Valores

In [14]:
array_03 = np.array([1,2,3], dtype=np.float32)
print(array_03)
print(array_03.dtype)

[1. 2. 3.]
float32


In [15]:
array_04 = np.array([1,2,3], dtype=np.int32)
print(array_04)
print(array_04.dtype)

[1 2 3]
int32


In [16]:
array_05 = np.array([1,2,3], dtype=np.float64)
print(array_05)
print(array_05.dtype)

[1. 2. 3.]
float64


## Convertendo Valores

In [17]:
array_07 = np.array([1,2,3], dtype=np.int32)
print(array_07.dtype)

# Convertendo 
array_07 = array_07.astype(float)
print(array_07.dtype)

int32
float64


## Array de string

In [18]:
array_05 = np.array(['um','dois','três'])
print(array_05)

['um' 'dois' 'três']
