In [20]:
import numpy as np

## Array 1D

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [21]:
# Criando um array 1 dimensão
ar_1d = np.random.randn(5)
print(ar_1d)
print(ar_1d.shape)

[ 0.09269779  0.62356185  1.23873313  0.10536906 -1.14644618]
(5,)


## Array 2D

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [22]:
# Criando um array com 2 linhas e 3 colunas
ar_2d = np.random.randn(2,3)
print(ar_2d)
print(ar_2d.shape)

[[-0.99304947 -0.69698667  0.40129979]
 [-0.01158379  0.73437481  1.54442894]]
(2, 3)


## Array 3D

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [23]:
# Criando um array com 3D
ar_3d = np.random.randn(1,3,2)
print(ar_3d)
print(ar_3d.shape)

[[[-0.20747014  1.22081803]
  [ 0.18527349 -0.6928934 ]
  [-0.01728003  0.60569365]]]
(1, 3, 2)


## Array 4D

In [24]:
ar_4d = np.random.randn(1,1,2,2)
print(ar_4d)
print(ar_4d.shape)

[[[[-0.87376079 -1.14666762]
   [ 0.86194981  1.07167247]]]]
(1, 1, 2, 2)


## Array 1D - Lista de Valores

In [25]:
array_01 = [1,2,3]
array_01 = np.array(array_01)
print(array_01)
print(type(array_01))

[1 2 3]
<class 'numpy.ndarray'>


## Array 2D - Lista de Valores

In [26]:
array_02 = [[1,2,3],[4,5,6]]
array_02 = np.array(array_02)
print(array_02)
print(type(array_02))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Array Com Valor Zero

In [27]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Com Valor Um

In [30]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Array de string

In [33]:
array_05 = np.array(['um','dois','três'])
print(array_05)

['um' 'dois' 'três']
