In [1]:
import numpy as np

## Array 1D

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [2]:
# Criando um array 1 dimensão
ar_1d = np.random.randn(2)
print(ar_1d)
print(ar_1d.shape)

[1.05335413 0.31432598]
(2,)


## Array 2D

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [3]:
# Criando um array com 2 linhas e 3 colunas
ar_2d = np.random.randn(2,3)
print(ar_2d)
print(ar_2d.shape)

[[-0.03354177 -0.21425838  0.62875015]
 [-0.36304752 -1.27659339 -0.35242954]]
(2, 3)


## Array 3D

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [4]:
# Criando um array com 3D
ar_3d = np.random.randn(2,3,5)
print(ar_3d)
print(ar_3d.shape)

[[[-1.62552825  0.94360741  0.0184239  -0.49139598 -1.50469343]
  [ 2.03838896 -0.86565214  0.44697039  0.85745717  1.27998673]
  [-0.53070739 -1.44000389 -1.8044138   0.97969716 -0.43352156]]

 [[ 1.63883124  0.41005465 -1.41692442  1.32419747  0.7630903 ]
  [ 0.72365031  1.02037424  1.13027625  1.60463485 -0.98481377]
  [ 0.50084636 -1.20817114  0.06807888 -0.01678538  1.50707357]]]
(2, 3, 5)


## Array 4D

In [5]:
ar_4d = np.random.randn(3,3,2,2)
print(ar_4d)
print(ar_4d.shape)

[[[[-0.98804578 -0.66803273]
   [ 1.47169869  0.49254464]]

  [[-1.61131089 -1.37351173]
   [-0.88150857 -0.04296118]]

  [[-0.94709358  0.06280852]
   [-1.07160092  0.34641896]]]


 [[[ 0.70294826 -0.13223053]
   [-0.31643536 -0.52727417]]

  [[ 0.46576598  0.03630911]
   [-0.77405957  2.97281153]]

  [[ 0.02585572  0.64280195]
   [-0.92795651 -0.36973134]]]


 [[[ 1.29633088  1.59589046]
   [-0.42797657  0.91943383]]

  [[ 0.24602983  0.7740874 ]
   [-0.10655421 -1.03571261]]

  [[-0.73985688 -1.59845812]
   [-0.7812887  -1.14485298]]]]
(3, 3, 2, 2)


## Array 1D - Lista de Valores

In [6]:
array_01 = [1,2,3]
array_01 = np.array(array_01)
print(array_01)
print(type(array_01))

[1 2 3]
<class 'numpy.ndarray'>


## Array 2D - Lista de Valores

In [7]:
array_02 = [[1,2,3],[4,5,6]]
array_02 = np.array(array_02)
print(array_02)
print(type(array_02))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Array Com Valor Zero

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Com Valor Um

In [11]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tipo de Valores

In [14]:
array_03 = np.array([1,2,3], dtype=np.float32)
print(array_03)
print(array_03.dtype)

[1. 2. 3.]
float32


In [15]:
array_04 = np.array([1,2,3], dtype=np.int32)
print(array_04)
print(array_04.dtype)

[1 2 3]
int32


In [16]:
array_05 = np.array([1,2,3], dtype=np.float64)
print(array_05)
print(array_05.dtype)

[1. 2. 3.]
float64


## Convertendo Valores

In [17]:
array_07 = np.array([1,2,3], dtype=np.int32)
print(array_07.dtype)

# Convertendo 
array_07 = array_07.astype(float)
print(array_07.dtype)

int32
float64


## Array de string

In [18]:
array_05 = np.array(['um','dois','três'])
print(array_05)

['um' 'dois' 'três']
