In [1]:
import numpy as np

## Array 1D

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [2]:
# Criando um array 1 dimensão
ar_1d = np.random.randn(2)
print(ar_1d)
print(ar_1d.shape)

[1.9754064  1.25642085]
(2,)


## Array 2D

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [3]:
# Criando um array com 2 linhas e 3 colunas
ar_2d = np.random.randn(2,3)
print(ar_2d)
print(ar_2d.shape)

[[-1.07020662 -1.79057743  0.70223   ]
 [-0.07344542  0.87144081  0.54928489]]
(2, 3)


## Array 3D

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [4]:
# Criando um array com 3D
ar_3d = np.random.randn(3,3,2)
print(ar_3d)
print(ar_3d.shape)

[[[ 1.01009153 -0.41929063]
  [ 1.1675175   0.19050641]
  [-0.71294075 -0.05653883]]

 [[-0.91274503  0.96947414]
  [-0.17136932 -0.28244546]
  [ 0.6344776   0.83504427]]

 [[-0.27480976  2.03794431]
  [-0.19274523  1.55173417]
  [-0.41245401 -0.07969016]]]
(3, 3, 2)


## Array 4D

In [5]:
ar_4d = np.random.randn(3,3,2,2)
print(ar_4d)
print(ar_4d.shape)

[[[[-1.08424555  0.86198644]
   [-0.50715518  0.64583788]]

  [[-1.0063966   1.5042224 ]
   [-1.22506296 -0.11229628]]

  [[ 0.97250256 -0.29085683]
   [-0.14289813 -2.11789663]]]


 [[[-0.09110528  0.54135001]
   [ 1.51755017  2.35898531]]

  [[-1.61559448 -0.92744947]
   [-0.94484484 -1.44453062]]

  [[ 1.36726032  0.43076503]
   [-0.44490671 -0.61603409]]]


 [[[ 0.42335118 -0.51065546]
   [ 1.33581399 -0.95117763]]

  [[ 0.545304    1.59820524]
   [ 0.32482983 -2.92255047]]

  [[ 0.45658032 -0.94458576]
   [-0.26936105 -0.7562757 ]]]]
(3, 3, 2, 2)


## Array 1D - Lista de Valores

In [6]:
array_01 = [1,2,3]
array_01 = np.array(array_01)
print(array_01)
print(type(array_01))

[1 2 3]
<class 'numpy.ndarray'>


## Array 2D - Lista de Valores

In [7]:
array_02 = [[1,2,3],[4,5,6]]
array_02 = np.array(array_02)
print(array_02)
print(type(array_02))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Array Com Valor Zero

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Com Valor Um

In [11]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tipo de Valores

In [14]:
array_03 = np.array([1,2,3], dtype=np.float32)
print(array_03)
print(array_03.dtype)

[1. 2. 3.]
float32


In [15]:
array_04 = np.array([1,2,3], dtype=np.int32)
print(array_04)
print(array_04.dtype)

[1 2 3]
int32


In [16]:
array_05 = np.array([1,2,3], dtype=np.float64)
print(array_05)
print(array_05.dtype)

[1. 2. 3.]
float64


## Convertendo Valores

In [17]:
array_07 = np.array([1,2,3], dtype=np.int32)
print(array_07.dtype)

# Convertendo 
array_07 = array_07.astype(float)
print(array_07.dtype)

int32
float64


## Array de string

In [18]:
array_05 = np.array(['um','dois','três'])
print(array_05)

['um' 'dois' 'três']
