In [3]:
import numpy as np

![imagem](https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png)

## Array 1D

In [7]:
# Criando um array 1 dimensão
ar_1d = np.random.randn(2)
print(ar_1d)
print(ar_1d.shape)

[-0.51959147  0.52396497]
(2,)


## Array 2D

In [6]:
# Criando um array com 2 linhas e 3 colunas
ar_2d = np.random.randn(2,3)
print(ar_2d)
print(ar_2d.shape)

[[-0.82487757 -0.16727285 -1.28670304]
 [ 1.08851055  0.11652764  1.18456957]]
(2, 3)


## Array 3D

In [23]:
# Criando um array com 3D
ar_3d = np.random.randn(3,3,2)
print(ar_3d)
print(ar_3d.shape)

[[[ 2.36783558  0.48191821]
  [ 0.29005202 -0.74966035]
  [ 1.00932267 -2.5213782 ]]

 [[ 1.20600515  2.89479781]
  [-0.31152565  0.87465077]
  [-0.4606654   0.50017355]]

 [[ 1.39228214 -0.70721926]
  [-0.47706857  0.79994752]
  [ 0.29889012 -0.07359996]]]
(3, 3, 2)


## Array 4D

In [24]:
ar_4d = np.random.randn(3,3,2,2)
print(ar_4d)
print(ar_4d.shape)

[[[[-0.82258549 -1.18682166]
   [-0.22053782  0.36167315]]

  [[-1.04619365  1.02893583]
   [-0.41665447 -0.46973288]]

  [[-0.15224864 -1.27433824]
   [ 1.36982707 -0.36384216]]]


 [[[-0.74660812 -0.5474117 ]
   [ 1.35566913 -0.00737826]]

  [[-0.32180118  1.15059834]
   [-0.33672796 -2.55554089]]

  [[ 0.3642831   1.33732477]
   [ 0.00600991  0.09791354]]]


 [[[-2.12629606 -0.62002013]
   [-0.87913774 -0.08589757]]

  [[ 1.36225719  2.42891737]
   [ 0.04332546 -0.0272779 ]]

  [[-0.61450664  0.19206335]
   [-0.8120834   0.90222688]]]]
(3, 3, 2, 2)


## Array 1D - Lista de Valores

In [26]:
array_01 = [1,2,3]
array_01 = np.array(array_01)
print(array_01)
print(type(array_01))

[1 2 3]
<class 'numpy.ndarray'>


## Array 2D - Lista de Valores

In [28]:
array_02 = [[1,2,3],[4,5,6]]
array_02 = np.array(array_02)
print(array_02)
print(type(array_02))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Array Com Valor Zero

In [33]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Com Valor Um

In [40]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [38]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
print(np.ones((2,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tipo de Valores

In [42]:
array_03 = np.array([1,2,3], dtype=np.float32)
print(array_03)
print(array_03.dtype)

[1. 2. 3.]
float32


In [44]:
array_04 = np.array([1,2,3], dtype=np.int32)
print(array_04)
print(array_04.dtype)

[1 2 3]
int32


In [46]:
array_05 = np.array([1,2,3], dtype=np.float64)
print(array_05)
print(array_05.dtype)

[1. 2. 3.]
float64


## Convertendo Valores

In [48]:
array_07 = np.array([1,2,3], dtype=np.int32)
print(array_07.dtype)

# Convertendo 
array_07 = array_07.astype(float)
print(array_07.dtype)

int32
float64


## Array de string

In [9]:
array_05 = np.array(['um','dois','três'])
print(array_05)

['um' 'dois' 'três']
