In [2]:
import numpy as np

In [3]:
ar_01 = np.array([[1,2,3],[4,5,6]])
print(ar_01)

[[1 2 3]
 [4 5 6]]


## Multiplicação

In [4]:
print(ar_01 * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
print(ar_01 * 100)

[[100 200 300]
 [400 500 600]]


## Divisão

In [6]:
# Observer que os valores eram do tipo inteiro e agora é do tipo float
print(ar_01 / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


## Soma

In [7]:
print(ar_01 + 100)

[[101 102 103]
 [104 105 106]]


## Subtração

In [8]:
print(ar_01 - 1)

[[0 1 2]
 [3 4 5]]


## Comparando 2 arrays

In [9]:
ar_02 = np.array([[1,2,3],[4,5,6]])
ar_03 = np.array([[4,5,6],[7,8,9]])

ar_02 > ar_03

array([[False, False, False],
       [False, False, False]])

In [21]:
ar_02 = np.array([[4,5,6],[1,2,3]])
ar_03 = np.array([[1,2,3],[7,8,9]])

ar_02 > ar_03

array([[ True,  True,  True],
       [False, False, False]])

In [22]:
print(ar_03 - ar_02)

[[-3 -3 -3]
 [ 6  6  6]]


In [23]:
print(ar_03 + ar_02)

[[ 5  7  9]
 [ 8 10 12]]


In [24]:
print(ar_03 / ar_02)

[[0.25 0.4  0.5 ]
 [7.   4.   3.  ]]


In [25]:
print(ar_03 * ar_02)

[[ 4 10 18]
 [ 7 16 27]]


## Transposta da matriz

In [26]:
ar_04 = np.random.randn(6,3)
print(ar_04)

[[ 0.03976512  0.43689736 -0.42897808]
 [ 0.49714627 -0.31034947 -0.78281079]
 [ 1.91164453  0.75065328  0.52616404]
 [-0.63191312 -0.71076625 -0.70316225]
 [ 0.77504987  0.50910825 -0.30909888]
 [-1.43356879  0.52274127 -0.26020723]]


In [27]:
ar_05 = np.transpose(ar_04)
print(ar_05)

[[ 0.03976512  0.49714627  1.91164453 -0.63191312  0.77504987 -1.43356879]
 [ 0.43689736 -0.31034947  0.75065328 -0.71076625  0.50910825  0.52274127]
 [-0.42897808 -0.78281079  0.52616404 -0.70316225 -0.30909888 -0.26020723]]


In [29]:
ar_04.T

array([[ 0.03976512,  0.49714627,  1.91164453, -0.63191312,  0.77504987,
        -1.43356879],
       [ 0.43689736, -0.31034947,  0.75065328, -0.71076625,  0.50910825,
         0.52274127],
       [-0.42897808, -0.78281079,  0.52616404, -0.70316225, -0.30909888,
        -0.26020723]])

In [31]:
print(ar_04.shape)
print(ar_04.T.shape)

(6, 3)
(3, 6)


In [33]:
# produto da matriz
print(np.dot(ar_05.T, ar_05))
print((np.dot(ar_05.T, ar_05).shape))

[[ 0.37648276  0.21998689  0.17826237 -0.0340188   0.38584465  0.28300144]
 [ 0.21998689  0.95626393  0.30551521  0.45687567  0.46927761 -0.67123282]
 [ 0.17826237  0.30551521  4.49471377 -2.11151097  1.70114692 -2.48498818]
 [-0.0340188   0.45687567 -2.11151097  1.39894    -0.63427448  0.71731198]
 [ 0.38584465  0.46927761  1.70114692 -0.63427448  0.95543564 -0.76452565]
 [ 0.28300144 -0.67123282 -2.48498818  0.71731198 -0.76452565  2.39608572]]
(6, 6)
