In [1]:
import numpy as np

In [2]:
ar_01 = np.array([[1,2,3],[4,5,6]])
print(ar_01)

[[1 2 3]
 [4 5 6]]


## Multiplicação

In [3]:
print(ar_01 * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [4]:
print(ar_01 * 100)

[[100 200 300]
 [400 500 600]]


## Divisão

In [5]:
# Observer que os valores eram do tipo inteiro e agora é do tipo float
print(ar_01 / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


## Soma

In [6]:
print(ar_01 + 100)

[[101 102 103]
 [104 105 106]]


## Subtração

In [7]:
print(ar_01 - 1)

[[0 1 2]
 [3 4 5]]


## Comparando 2 arrays

In [25]:
ar_02 = np.array([[1,2,3],[4,5,6]])
ar_03 = np.array([[4,5,6],[7,8,9]])

print(ar_03 > ar_02)

[[ True  True  True]
 [ True  True  True]]


In [26]:
print(ar_03 < ar_02)

[[False False False]
 [False False False]]


In [27]:
print(ar_03 == ar_02)

[[False False False]
 [False False False]]


In [28]:
print(ar_03 != ar_02)

[[ True  True  True]
 [ True  True  True]]


## Opreção entre arrays

In [12]:
print(ar_03 - ar_02)

[[-3 -3 -3]
 [ 6  6  6]]


In [13]:
print(ar_03 + ar_02)

[[ 5  7  9]
 [ 8 10 12]]


In [14]:
print(ar_03 / ar_02)

[[0.25 0.4  0.5 ]
 [7.   4.   3.  ]]


In [15]:
print(ar_03 * ar_02)

[[ 4 10 18]
 [ 7 16 27]]


## Transposta da matriz

In [30]:
ar_04 = np.random.randn(6,3)
print(ar_04)

[[ 0.06602939  0.28682194 -0.59393715]
 [ 0.51146661  0.72902029 -1.20245125]
 [-0.97118928 -1.47056868 -1.89411247]
 [ 1.35589447 -0.04612108  0.34797932]
 [ 0.6125759  -2.06669193 -0.27742747]
 [ 0.95274574  1.96280198  0.28933024]]


In [31]:
ar_05 = np.transpose(ar_04)
print(ar_05)

[[ 0.06602939  0.51146661 -0.97118928  1.35589447  0.6125759   0.95274574]
 [ 0.28682194  0.72902029 -1.47056868 -0.04612108 -2.06669193  1.96280198]
 [-0.59393715 -1.20245125 -1.89411247  0.34797932 -0.27742747  0.28933024]]


In [32]:
ar_04.T

array([[ 0.06602939,  0.51146661, -0.97118928,  1.35589447,  0.6125759 ,
         0.95274574],
       [ 0.28682194,  0.72902029, -1.47056868, -0.04612108, -2.06669193,
         1.96280198],
       [-0.59393715, -1.20245125, -1.89411247,  0.34797932, -0.27742747,
         0.28933024]])

In [33]:
print(ar_04.shape)
print(ar_04.T.shape)

(6, 3)
(3, 6)


In [34]:
# produto da matriz
print(np.dot(ar_05.T, ar_05))
print((np.dot(ar_05.T, ar_05).shape))

[[ 0.43938804  0.95705131  0.63906536 -0.1303775  -0.3875501   0.45403992]
 [ 0.95705131  2.23895768  0.7087726   0.24144337 -0.85975523  1.57031459]
 [ 0.63906536  0.7087726   6.69344292 -1.90811794  2.96976411 -4.3597556 ]
 [-0.1303775   0.24144337 -1.90811794  1.96166657  0.8293673   1.30197708]
 [-0.3875501  -0.85975523  2.96976411  0.8293673   4.72343075 -3.55314609]
 [ 0.45403992  1.57031459 -4.3597556   1.30197708 -3.55314609  4.84402805]]
(6, 6)


## Produto da Matriz

In [36]:
ar_06 = np.random.randn(2,3)
print(ar_06)

[[-1.28490211  0.34510777 -0.66425383]
 [-1.64705756  1.76126538 -1.21508529]]


In [37]:
ar_07 = np.random.randn(3,2)
print(ar_07)

[[-0.63613188  1.04162429]
 [ 0.15829356  1.30184907]
 [ 1.56009835 -0.17869165]]


In [39]:
print(np.dot(ar_06, ar_07))

[[-0.16430577 -0.7704104 ]
 [-0.56910978  0.79441213]]
