In [69]:
import numpy as np

## Indexação básica e fatiamento 

In [70]:
ar_01 = np.arange(10)
print(ar_01)

[0 1 2 3 4 5 6 7 8 9]


## Primeiro elemento 

In [71]:
ar_01[0]

0

## Último elemento 

In [72]:
ar_01[-1]

9

In [73]:
ar_01[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
ar_01[-2]

8

In [75]:
ar_01[-2:]

array([8, 9])

In [76]:
# O index de número 3 é excluiso e representa o 4º elemento do array
# Significa indice 1 ate o indice 3 excluindo o indice 3
ar_01[1:3]

array([1, 2])

## Substituindo Valores

In [77]:
ar_01[1] = 11

ar_01

array([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

## Array 2D Slice

In [78]:
ar_02 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar_02

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# Indice 0,0
ar_02[0][0]

1

In [80]:
# Indice 0,0
ar_02[0][2]

3

In [81]:
# Pega a linha de indice 0
ar_02[0]

array([1, 2, 3])

In [82]:
# Pega a linha de indice 0 e coluna de indice 1 
ar_02[0][1]

2

In [83]:
# Pega a linha de indice 0 até o indice 1 exclusico
ar_02[0:1]

array([[1, 2, 3]])

In [84]:
# Pega a linha de indice 0 até o indice 2 exclusico
ar_02[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
ar_02[1:3,1:]

array([[5, 6],
       [8, 9]])

In [86]:
ar_02[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## Array 3D Slice

In [87]:
ar_03 = np.random.rand(3,3,3)
ar_03

array([[[0.04182155, 0.79073253, 0.46913249],
        [0.8986215 , 0.22595116, 0.88147886],
        [0.55149422, 0.86872795, 0.91510351]],

       [[0.54683964, 0.47991572, 0.58612895],
        [0.46724074, 0.31889892, 0.99365768],
        [0.89739254, 0.28138822, 0.94689883]],

       [[0.68307808, 0.53913998, 0.23187353],
        [0.85442994, 0.9326403 , 0.31917312],
        [0.67143958, 0.60211858, 0.41688702]]])

In [88]:
ar_03[0][0][0]

0.041821551669015355

In [89]:
ar_03[1][0][1]

0.47991571630246865

In [93]:
ar_03[2][2][1]

0.6021185785488554

In [91]:
ar_03[2][1:3][:2]

array([[0.85442994, 0.9326403 , 0.31917312],
       [0.67143958, 0.60211858, 0.41688702]])

In [97]:
ar_03[2][1][1:3]

array([0.9326403 , 0.31917312])