In [1]:
import numpy as np

## Indexação básica e fatiamento 

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [2]:
ar_01 = np.arange(10)
print(ar_01)

[0 1 2 3 4 5 6 7 8 9]


## Primeiro elemento 

In [3]:
ar_01[0]

0

In [4]:
ar_01[3]

3

## Último elemento 

In [5]:
ar_01[-1]

9

In [6]:
ar_01[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
ar_01[-2]

8

In [8]:
ar_01[-2:]

array([8, 9])

In [9]:
# O index de número 3 é excluiso e representa o 4º elemento do array
# Significa indice 1 ate o indice 3 excluindo o indice 3
ar_01[1:3]

array([1, 2])

## Substituindo Valores

In [10]:
ar_01[1] = 11

ar_01

array([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

## Array 2D Slice

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [11]:
ar_02 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar_02

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Pega a linha de indice 0
ar_02[0]

array([1, 2, 3])

In [13]:
# Indice 0,0
ar_02[0][0]

1

In [14]:
# Indice 0,0
ar_02[0][2]

3

In [15]:
# Pega a linha de indice 0 e coluna de indice 1 
ar_02[0][1]

2

In [16]:
# Pega a linha de indice 0 até o indice 1 exclusico
ar_02[0:1]

array([[1, 2, 3]])

In [17]:
# Pega a linha de indice 0 até o indice 2 exclusico
ar_02[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
ar_02[1:3,1:]

array([[5, 6],
       [8, 9]])

In [19]:
ar_02[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## Array 3D Slice

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [27]:
ar_03 = np.random.rand(3,4,2)
print(ar_03)
print(ar_03.shape)

[[[0.10637606 0.58127025]
  [0.08064695 0.31660941]
  [0.55777374 0.63368537]
  [0.23533312 0.48158705]]

 [[0.42625583 0.23830755]
  [0.58934429 0.67355429]
  [0.04006417 0.92652568]
  [0.33804986 0.97563281]]

 [[0.42995733 0.40490083]
  [0.94858489 0.14054847]
  [0.07500205 0.45601303]
  [0.97574401 0.88452854]]]
(3, 4, 2)


In [21]:
ar_03[0][0][0]

0.4963948416019235

In [22]:
ar_03[1][0][1]

0.36891510922295934

In [23]:
ar_03[2][2][1]

0.29574816243855373

In [24]:
ar_03[2][1:3][:2]

array([[0.54066645, 0.26068375],
       [0.10953677, 0.29574816]])

In [25]:
ar_03[2][1][1:3]

array([0.26068375])