In [54]:
import numpy as np

## Indexação básica e fatiamento 

![imagem](https://www.ankitweblogic.com/images/1d-array.png)

In [55]:
ar_01 = np.arange(10)
print(ar_01)

[0 1 2 3 4 5 6 7 8 9]


## Primeiro elemento 

In [56]:
ar_01[0]

0

In [57]:
ar_01[3]

3

## Último elemento 

In [58]:
ar_01[-1]

9

In [59]:
ar_01[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
ar_01[-2]

8

In [61]:
ar_01[-2:]

array([8, 9])

In [62]:
# O index de número 3 é excluiso e representa o 4º elemento do array
# Significa indice 1 ate o indice 3 excluindo o indice 3
ar_01[1:3]

array([1, 2])

## Substituindo Valores

In [63]:
ar_01[1] = 11

ar_01

array([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

## Array 2D Slice

![imagem](https://www.oreilly.com/api/v2/epubs/9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png)

In [64]:
ar_02 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar_02

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# Pega a linha de indice 0
ar_02[0]

array([1, 2, 3])

In [66]:
# Indice 0,0
ar_02[0][0]

1

In [67]:
# Indice 0,0
ar_02[0][2]

3

In [68]:
# Pega a linha de indice 0 e coluna de indice 1 
ar_02[0][1]

2

In [69]:
# Pega a linha de indice 0 até o indice 1 exclusico
ar_02[0:1]

array([[1, 2, 3]])

In [70]:
# Pega a linha de indice 0 até o indice 2 exclusico
ar_02[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
ar_02[1:3,1:]

array([[5, 6],
       [8, 9]])

In [72]:
ar_02[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## Array 3D Slice

![imagem](https://ipython-books.github.io/pages/chapter01_basic/images/numpy.png)

In [73]:
ar_03 = np.random.rand(3,4,2)
ar_03

array([[[0.23719072, 0.84334888],
        [0.60244105, 0.58647465],
        [0.65641749, 0.19019578],
        [0.23289665, 0.61950607]],

       [[0.77768541, 0.09834956],
        [0.47418696, 0.74668871],
        [0.3674639 , 0.87323945],
        [0.5263178 , 0.28688357]],

       [[0.43668412, 0.24134254],
        [0.20870485, 0.14912341],
        [0.38547741, 0.07525531],
        [0.43086442, 0.79545575]]])

In [74]:
ar_03[0][0][0]

0.23719072110545603

In [75]:
ar_03[1][0][1]

0.09834956261341243

In [76]:
ar_03[2][2][1]

0.07525530605890662

In [77]:
ar_03[2][1:3][:2]

array([[0.20870485, 0.14912341],
       [0.38547741, 0.07525531]])

In [78]:
ar_03[2][1][1:3]

array([0.14912341])