In [1]:
import numpy as np

In [2]:
ar_01 = np.random.randn(6,3)
print(ar_01)

[[ 0.17324639  0.26518757  0.47224097]
 [ 1.61101725 -0.02410673  0.44277882]
 [ 0.29690699  1.07896758  0.71094957]
 [ 0.44545841 -0.91919251  0.47101186]
 [-0.26422148 -0.25234098  0.04721606]
 [ 0.05185394 -0.66484956 -0.51205045]]


In [3]:
# Média
ar_01.mean()

0.1905596503797979

In [4]:
# Soma de todos os valores
ar_01.sum()

3.4300737068363625

In [5]:
# Desvio padrão
ar_01.std()

0.5928897941825165

In [6]:
ar_01.max()

1.6110172504673774

In [7]:
ar_01.min()

-0.9191925134470237

## Coluna | Linha

In [8]:
# Soma pela linha
ar_01.sum(axis=0)

array([ 2.31426151, -0.51633463,  1.63214683])

In [9]:
# Soma pela coluna
ar_01.sum(axis=1)

array([ 0.91067494,  2.02968934,  2.08682414, -0.00272224, -0.4693464 ,
       -1.12504607])

In [10]:
# Soma pela coluna
ar_01.mean(axis=1)

array([ 0.30355831,  0.67656311,  0.69560805, -0.00090741, -0.1564488 ,
       -0.37501536])

## Correlação

In [11]:
np.corrcoef(ar_01)

array([[ 1.        , -0.52066942,  0.33239365,  0.23263616,  0.96344745,
        -0.58483757],
       [-0.52066942,  1.        , -0.97828151,  0.70920798, -0.27291798,
         0.99703351],
       [ 0.33239365, -0.97828151,  1.        , -0.8399378 ,  0.06757887,
        -0.95942531],
       [ 0.23263616,  0.70920798, -0.8399378 ,  1.        ,  0.48468004,
         0.6528412 ],
       [ 0.96344745, -0.27291798,  0.06757887,  0.48468004,  1.        ,
        -0.34615518],
       [-0.58483757,  0.99703351, -0.95942531,  0.6528412 , -0.34615518,
         1.        ]])