In [82]:
import numpy as np
import pandas as pd

import statistics

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [10]:
ar_01 = np.random.randint(100, size=10)
print(ar_01)

[80 34 84  3  0 70 88 28 16 66]


In [15]:
print(ar_01)

[80 34 84  3  0 70 88 28 16 66]


### Soma

In [24]:
# Soma de todos os valores
ar_01.sum()

469

### Mínimo 

In [55]:
ar_01.min()

0

### Máximo

In [56]:
ar_01.max()

88

### Média

In [1]:
print(ar_01.mean())

NameError: name 'ar_01' is not defined

## Mediana

In [14]:
# Mediana
print(np.median(ar_01))

50.0


### Moda

In [21]:
print(statistics.mode(ar_01))

80


In [22]:
ar_02 = np.append(ar_01,3)

In [23]:
print(statistics.mode(ar_02))

3


### Desvio Padrão

In [25]:
ar_01.std()

32.65715848018623

In [57]:
ar_01.sum()

469

## Coluna | Linha

In [ ]:
ar_01

In [8]:
# Soma pela linha
ar_01.sum(axis=0)

array([ 2.31426151, -0.51633463,  1.63214683])

In [9]:
# Soma pela coluna
ar_01.sum(axis=1)

array([ 0.91067494,  2.02968934,  2.08682414, -0.00272224, -0.4693464 ,
       -1.12504607])

In [10]:
# Soma pela coluna
ar_01.mean(axis=1)

array([ 0.30355831,  0.67656311,  0.69560805, -0.00090741, -0.1564488 ,
       -0.37501536])