# Reshape

In [1]:
import numpy as np

## 1D para 2D

In [2]:
ar_01 = np.arange(8)
print(ar_01)

[0 1 2 3 4 5 6 7]


In [6]:
# 4 linhas e 2 colunas
print(ar_01.reshape(1,-1))

[[0 1 2 3 4 5 6 7]]


## 1D para 3D

In [15]:
# 4 linhas e 2 colunas
print(ar_01.reshape(1,-1,1))

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]]]


## 2D para 3D

In [23]:
# 4 linhas e 2 colunas
ar_02 = np.array([[1, 2, 3,4, 5, 6], [7,8,9,10,11,12]])
print(ar_02)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
print(ar_02.reshape(-1,1,1))

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


## 3D para 2D

In [28]:
ar_03 = ar_02.reshape(-1,1,1)
print(ar_03)

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


In [30]:
print(ar_03.reshape(-1,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


## 3D para 2D Flatten

In [31]:
print(ar_03)

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


In [32]:
print(ar_03.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 2D para 1D

In [33]:
print(ar_02)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [34]:
print(ar_02.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Criando o array com o reshape

In [40]:
ar_06 = np.arange(15).reshape((-1))
print(ar_06)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
ar_03 = np.arange(15).reshape((5,3))
print(ar_03)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
ar_04 = np.arange(15).reshape((-1,3,5))
print(ar_04)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
