# Reshape

In [1]:
import numpy as np

## 1D para 2D

In [2]:
ar_01 = np.arange(8)
print(ar_01)

[0 1 2 3 4 5 6 7]


In [3]:
# 4 linhas e 2 colunas
ar_01.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [4]:
# 2 linhas e 4 colunas
ar_01.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
print(ar_01)

[0 1 2 3 4 5 6 7]


In [6]:
ar_01 = ar_01.reshape((4,2))
print(ar_01)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## 2D para 3D

In [7]:
print(ar_01.reshape(4,2,1))

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]


In [8]:
ar_3d = ar_01.reshape(4,2,1)
print(ar_3d.shape)
print(ar_3d.reshape(4,2).shape)
print(ar_3d.reshape(-1).shape)

(4, 2, 1)
(4, 2)
(8,)


## Flatten

In [9]:
print(ar_3d)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]


In [10]:
print(ar_3d.flatten())

[0 1 2 3 4 5 6 7]


In [11]:
print(ar_3d.ravel())

[0 1 2 3 4 5 6 7]


# 1,-1

In [19]:
ar_02 = np.arange(15)
print(ar_02.shape)
print(ar_02)

(15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
print(ar_02.reshape((1,-1)).shape)
print(ar_02.reshape((1,-1)))

(1, 15)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


## Criando o array com o reshape

In [17]:
ar_03 = np.arange(15).reshape((5,3))
print(ar_03)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
