# Reshape

In [1]:
import numpy as np

## 1D para 2D

In [2]:
ar_01 = np.arange(8)
print(ar_01)

[0 1 2 3 4 5 6 7]


In [3]:
# 4 linhas e 2 colunas
print(ar_01.reshape(1,-1))

[[0 1 2 3 4 5 6 7]]


## 1D para 3D

In [4]:
# 4 linhas e 2 colunas
print(ar_01.reshape(1,-1,1))

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]]]


## 2D para 3D

In [5]:
# 4 linhas e 2 colunas
ar_02 = np.array([[1, 2, 3,4, 5, 6], [7,8,9,10,11,12]])
print(ar_02)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
print(ar_02.reshape(-1,1,1))

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


## 3D para 2D

In [18]:
ar_03 = ar_02.reshape(-1,1,1)
print(ar_03)

[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


In [19]:
print(ar_03.reshape(-1,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [20]:
print(ar_03.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
