# Concaternar 

In [1]:
import numpy as np

In [2]:
ar_01 = np.array([[1,2,3],[4,5,6]])
ar_02 = np.array([[7,8,9],[10,11,12]])

In [3]:
print(ar_01)

[[1 2 3]
 [4 5 6]]


In [4]:
print(ar_02)

[[ 7  8  9]
 [10 11 12]]


In [6]:
# axis=0 refere a junção por linhas
print(np.concatenate([ar_01,ar_02],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# axis=1 refere a junção por coluna
print(np.concatenate([ar_01,ar_02],axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [7]:
print(np.append(ar_01,ar_02))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
# Concatena por linhas
print(np.vstack((ar_01,ar_02)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# Concatena por coluna
print(np.hstack((ar_01,ar_02)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
