# Concaternar 

In [1]:
import numpy as np

In [2]:
ar_01 = np.array([[1,2,3],[4,5,6]])
ar_02 = np.array([[7,8,9],[10,11,12]])

In [3]:
print(ar_01)

[[1 2 3]
 [4 5 6]]


In [4]:
print(ar_02)

[[ 7  8  9]
 [10 11 12]]


In [5]:
# axis=0 refere a junção por linhas
print(np.concatenate([ar_01,ar_02],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# axis=1 refere a junção por coluna
print(np.concatenate([ar_01,ar_02],axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
print(np.append(ar_01,ar_02))

In [7]:
# Concatena por linhas
print(np.vstack((ar_01,ar_02)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# Concatena por coluna
print(np.hstack((ar_01,ar_02)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Split

In [9]:
ar_03 = np.random.randn(5,2)
print(ar_03.shape)

(5, 2)


In [10]:
um, dois, tres = np.split(ar_03, [1,3])

In [11]:
print(um.shape)

(1, 2)


In [12]:
print(dois.shape)

(2, 2)


In [13]:
print(tres.shape)

(2, 2)


In [14]:
ar_04 = np.random.randn(100,2)
print(ar_04.shape)

(100, 2)


In [15]:
# Número de linhas
ar_04.shape[0]

100

In [16]:
# Número de colunas
ar_04.shape[1]

2

In [17]:
vl = ar_04.shape[0] - (ar_04.shape[0] * 0.2)
ar_05 = ar_04[:int(vl)]
print(ar_05.shape)

(80, 2)


In [18]:
vl = ar_04.shape[0] - (ar_04.shape[0] * 0.8)
ar_06 = ar_04[(int(vl)*-1):]
print(ar_06.shape)

(20, 2)
