In [1]:
import numpy as np

## Ordenando por números

In [2]:
arr_01 = np.random.rand(5)
print(arr_01)

[0.29230364 0.90413898 0.87825103 0.09732731 0.0483455 ]


In [3]:
np.sort(arr_01)

array([0.0483455 , 0.09732731, 0.29230364, 0.87825103, 0.90413898])

In [4]:
arr_02 = np.random.rand(5,5)
print(arr_02)

[[0.75861716 0.66238915 0.66018288 0.71596214 0.35403563]
 [0.47367151 0.65260132 0.2216609  0.69945258 0.92556807]
 [0.06265551 0.73682477 0.88954826 0.55910383 0.03118698]
 [0.70102033 0.20298702 0.60368392 0.80160723 0.3227377 ]
 [0.80117431 0.16523139 0.58251065 0.22348708 0.05166417]]


In [5]:
# Ordenação por linha
np.sort(arr_02)

array([[0.35403563, 0.66018288, 0.66238915, 0.71596214, 0.75861716],
       [0.2216609 , 0.47367151, 0.65260132, 0.69945258, 0.92556807],
       [0.03118698, 0.06265551, 0.55910383, 0.73682477, 0.88954826],
       [0.20298702, 0.3227377 , 0.60368392, 0.70102033, 0.80160723],
       [0.05166417, 0.16523139, 0.22348708, 0.58251065, 0.80117431]])

In [6]:
# Mostra o índice de cada valor 
arr_02.argsort()

array([[4, 2, 1, 3, 0],
       [2, 0, 1, 3, 4],
       [4, 0, 3, 1, 2],
       [1, 4, 2, 0, 3],
       [4, 1, 3, 2, 0]], dtype=int64)

## Ordenando Strings

In [7]:
nome = np.array(['Ana','João','Maria','Sebastiana'])
sobre_nome = np.array(['Silva','Batista','Santos','Gomes'])

In [10]:
# Ordenando pelo sobrenome e nome
ordem = np.sort(nome)
ordem

array(['Ana', 'João', 'Maria', 'Sebastiana'], dtype='<U10')

In [12]:
ordem = np.sort(sobre_nome)
ordem

array(['Batista', 'Gomes', 'Santos', 'Silva'], dtype='<U7')