In [20]:
import numpy as np

## Ordenando

In [21]:
arr_01 = np.random.rand(5)
print(arr_01)

[0.62122797 0.23284861 0.16279825 0.34744673 0.74870923]


In [22]:
np.sort(arr_01)

array([0.16279825, 0.23284861, 0.34744673, 0.62122797, 0.74870923])

In [23]:
arr_02 = np.random.rand(5,5)
print(arr_02)

[[0.8730654  0.47885146 0.98033076 0.43886953 0.53061035]
 [0.96116489 0.85145212 0.6174809  0.60305891 0.03344561]
 [0.38954185 0.42899515 0.74822087 0.03359456 0.12822369]
 [0.83355226 0.23372655 0.06290057 0.97140126 0.38684019]
 [0.43984727 0.97286066 0.16172447 0.16044603 0.30476116]]


In [24]:
# Ordenação por linha
np.sort(arr_02)

array([[0.43886953, 0.47885146, 0.53061035, 0.8730654 , 0.98033076],
       [0.03344561, 0.60305891, 0.6174809 , 0.85145212, 0.96116489],
       [0.03359456, 0.12822369, 0.38954185, 0.42899515, 0.74822087],
       [0.06290057, 0.23372655, 0.38684019, 0.83355226, 0.97140126],
       [0.16044603, 0.16172447, 0.30476116, 0.43984727, 0.97286066]])

In [31]:
# Mostra o índice de cada valor 
arr_02.argsort()

array([[3, 1, 4, 0, 2],
       [4, 3, 2, 1, 0],
       [3, 4, 0, 1, 2],
       [2, 1, 4, 0, 3],
       [3, 2, 4, 0, 1]], dtype=int64)

In [30]:
# Ordenando por coluna
print(arr_02[arr_02[:, 0].argsort()])

[[0.38954185 0.42899515 0.74822087 0.03359456 0.12822369]
 [0.43984727 0.97286066 0.16172447 0.16044603 0.30476116]
 [0.83355226 0.23372655 0.06290057 0.97140126 0.38684019]
 [0.8730654  0.47885146 0.98033076 0.43886953 0.53061035]
 [0.96116489 0.85145212 0.6174809  0.60305891 0.03344561]]


## Ordenando Strings

In [26]:
nome = np.array(['Ana','João','Maria','Sebastiana'])

In [27]:
# Ordenando pelo sobrenome e nome
ordem = np.sort(nome)
ordem

array(['Ana', 'João', 'Maria', 'Sebastiana'], dtype='<U10')