In [1]:
import numpy as np

## Apende para juntar 2 arrays

In [2]:
ar_01 = np.arange(5)
print(ar_01)

[0 1 2 3 4]


In [3]:
ar_02 = np.arange(5)
print(ar_02)

[0 1 2 3 4]


In [4]:
ar_03 = np.append(ar_01,ar_02)
print(ar_03)

[0 1 2 3 4 0 1 2 3 4]


# Inserir

In [5]:
# Insere um valor no final do array
print(np.append(ar_01,10))

[ 0  1  2  3  4 10]


# Atualizar

In [6]:
# Precisa fornecer o index
ar_01[1] = 59
print(ar_01)

[ 0 59  2  3  4]


## Deletar

In [7]:
# Precisa fornecer o index
print(ar_01)
print(np.delete(ar_01,1))

[ 0 59  2  3  4]
[0 2 3 4]


In [9]:
import pandas as pd

df = pd.DataFrame(ar_01, columns=['Numero'])

df

Numero
0       0
1      59
2       2
3       3
4       4