In [48]:
import numpy as np

## Apende para juntar 2 arrays

In [49]:
ar_01 = np.arange(5)
print(ar_01)

[0 1 2 3 4]


In [50]:
ar_02 = np.arange(5)
print(ar_02)

[0 1 2 3 4]


In [51]:
ar_03 = np.append(ar_01,ar_02)
print(ar_03)

[0 1 2 3 4 0 1 2 3 4]


# Inserir

In [52]:
# Insere um valor no final do array
ar_01 = np.append(ar_01,10)
print(ar_01)

[ 0  1  2  3  4 10]


# Atualizar

In [53]:
# Precisa fornecer o index
ar_01 = np.arange(5)
print(ar_01)

[0 1 2 3 4]


In [54]:
# Busca pelo valor
item = np.where(ar_01 == 4)

In [55]:
posicao = item[0][0]
ar_01[posicao] = 999
ar_01

array([  0,   1,   2,   3, 999])

## Deletar

In [56]:
# Precisa fornecer o index
print(ar_01)
print(np.delete(ar_01,1))

[  0   1   2   3 999]
[  0   2   3 999]
