In [1]:
import numpy as np

## Filtro

In [2]:
ar_01 = np.arange(15)
print(ar_01)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print(ar_01[ar_01 > 5])

[ 6  7  8  9 10 11 12 13 14]


In [4]:
print(ar_01[ar_01 <= 2])

[0 1 2]


In [5]:
print(ar_01[ar_01 % 2 == 0])

[ 0  2  4  6  8 10 12 14]
