In [1]:
import numpy as np

## Filtro

In [2]:
ar_01 = np.arange(15)
print(ar_01)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print(ar_01[ar_01 > 5])

[ 6  7  8  9 10 11 12 13 14]


In [4]:
print(ar_01[ar_01 <= 2])

[0 1 2]


In [5]:
print(ar_01[ar_01 % 2 == 0])

[ 0  2  4  6  8 10 12 14]


In [6]:
print(ar_01[ar_01 % 2 != 0])

[ 1  3  5  7  9 11 13]


In [7]:
print(ar_01[np.logical_and(ar_01 > 5, ar_01 < 8)])

[6 7]


In [8]:
print(ar_01[np.logical_and( ar_01 % 2 == 0 , ar_01 < 6)])

[0 2 4]


In [9]:
print(np.where(ar_01 < 7, ar_01 * 2,0))

[ 0  2  4  6  8 10 12  0  0  0  0  0  0  0  0]
